### ISSUE TITLE
[Minecraft/Bungeecord] Error on startup: "tput: not found"

### ISSUE THREAD

**Issue by beschio** [Pterodactyl/Dockerfiles#2]
Hey! When running the container, it spits out 3 errors caused by [the usage of tput](https://github.com/Pterodactyl/Docker-Minecraft/blob/940368803630f70e3c65546c0af833d85f9a5993/entry.sh#L4-L6) without it being installed:
```
/entry.sh: line 4: tput: not found
/entry.sh: line 5: tput: not found
/entry.sh: line 6: tput: not found
```

It's not really a big deal, the container works fine. But I'd recommend either:
  - [Installing tput in the container](https://github.com/Pterodactyl/Docker-Minecraft/pull/4). This would slightly increase the base container filesize, but also fix colors.
  - [Removing the usage of tput](https://github.com/Pterodactyl/Docker-Minecraft/pull/5). This would fix the error, but also remove the colors.

Depending on which option you choose (fix or remove) please merge the corresponding PR and close the other. 

Thanks a bunch!

**Comment by parkervcp** [comment]
Not actually a problem as far as I know. It's just some extra messaging. I will work on removing them from the containers.

**Comment by beschio** [comment]
I agree, it doesn't cause a problem. Please see the linked PRs for an already fixed image. Ideally [#7](https://github.com/Pterodactyl/Docker-Minecraft/pull/7) for @electronicboy's fix which has the best of both of mine.
